name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Check if project directory exists
      run: |
        ls DOE522-SA  # Replace with your actual project directory
        ls DOE522-SA/package.json  # Replace with your actual project directory and package file
      continue-on-error: true
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14
    
    - name: Install dependencies
      run: |
        cd DOE522-SA  # Replace with your actual project directory
        npm install
      
    - name: Build and Test
      run: |
        cd DOE522-SA  # Replace with your actual project directory
        npm run build

  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Deploy to Staging
      run: |
        # Add your deployment steps here
        echo "Deployment steps for staging"
